[workspace]

members = ["crates/eapp-utils", "crates/script-caller"]
resolver = "2"

[workspace.dependencies]
eframe = { version = "0.26.2", default-features = false }
eapp-utils = { version = "0.1.0", path = "crates/eapp-utils", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
image = { version = "0.24", default-features = false }
