name: Multi-Platform Release Build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  RUST_VERSION: "stable"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        crate: ["lonote", "manga-reader", "save-manager", "script-caller", "syncer", "your-player"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
            platform: linux
            RUSTFLAGS: "-C opt-level=z -C link-arg=-fuse-ld=lld"
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
            platform: macos
            RUSTFLAGS: "-C opt-level=z"
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
            platform: windows
            RUSTFLAGS: "-C target-feature=+crt-static"

    name: Build ${{ matrix.crate }} for ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.target }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            lld \
            libx11-dev \
            libgl1-mesa-dev \
            libasound2-dev \
            libfontconfig1-dev \
            libglib2.0-dev \
            libcairo2-dev \
            libpango1.0-dev \
            libatk1.0-dev \
            libgdk-pixbuf-2.0-dev \
            libssl-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libxkbcommon-dev \
            pkg-config \
            libgtk-3-dev

          if [ "${{ matrix.crate }}" == "your-player" ]; then
            sudo apt-get install -y libmpv-dev
          fi
      
      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest' && matrix.crate == 'your-player'
        shell: bash
        run: |
          # 安装 Rosetta 2（仅当未安装时）
          if ! /usr/bin/pgrep -q oahd; then
            echo "Installing Rosetta 2..."
            sudo softwareupdate --install-rosetta --agree-to-license
          fi
          
          # 在隔离路径安装 x86_64 Homebrew
          BREW_PREFIX="/usr/local/homebrew-x86"
          [ -d "$BREW_PREFIX" ] || sudo mkdir -p "$BREW_PREFIX"
          sudo chown -R $(whoami) "$BREW_PREFIX"
          
          # 使用临时文件避免引号嵌套问题
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh -o brew-install.sh
          chmod +x brew-install.sh
          
          # 安装 Homebrew - 使用环境变量指定安装路径
          echo "Installing Homebrew to $BREW_PREFIX..."
          HOMEBREW_PREFIX="$BREW_PREFIX" arch -x86_64 /bin/bash -c "NONINTERACTIVE=1 CI=1 ./brew-install.sh"
          
          # 设置环境
          echo "HOMEBREW_PREFIX=$BREW_PREFIX" >> $GITHUB_ENV
          echo "PATH=$BREW_PREFIX/bin:$BREW_PREFIX/sbin:$PATH" >> $GITHUB_ENV
          
          # 安装 mpv
          brew install mpv --cask
          
          # 设置库路径
          echo "LIBRARY_PATH=$BREW_PREFIX/lib:$LIBRARY_PATH" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=$BREW_PREFIX/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$BREW_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
          
          # 添加链接器搜索路径（合并原有优化标志）
          echo "RUSTFLAGS=-L$BREW_PREFIX/lib ${{ matrix.RUSTFLAGS }}" >> $GITHUB_ENV


      - name: Build ${{ matrix.crate }}
        shell: bash
        run: |
          cargo build --release --target ${{ matrix.target }} --bin ${{ matrix.crate }}
        env:
          CARGO_TERM_COLOR: always
          RUSTFLAGS: ${{ env.RUSTFLAGS || matrix.RUSTFLAGS }}
          LIBRARY_PATH: ${{ env.LIBRARY_PATH || '' }}
          DYLD_LIBRARY_PATH: ${{ env.DYLD_LIBRARY_PATH || '' }}
          PKG_CONFIG_PATH: ${{ env.PKG_CONFIG_PATH || '' }}

      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p release
          EXE_PATH="target/${{ matrix.target }}/release/${{ matrix.crate }}${{ matrix.ext }}"
          OUTPUT_NAME="${{ matrix.crate }}-${{ matrix.platform }}${{ matrix.ext }}"
          
          # 确保文件存在
          if [ -f "$EXE_PATH" ]; then
            cp "$EXE_PATH" "release/$OUTPUT_NAME"
          else
            echo "Error: Executable not found at $EXE_PATH"
            ls -la "target/${{ matrix.target }}/release/" || true
            exit 1
          fi

      - name: Strip symbols (Linux/macOS)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          FILE="release/${{ matrix.crate }}-${{ matrix.platform }}"
          if [ -f "$FILE" ]; then
            strip "$FILE"
          else
            echo "Error: File to strip not found: $FILE"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.crate }}-${{ matrix.platform }}
          path: release/*

  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*'
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref_name }}"
          body: |
            ## Multi-platform Executables
            
            **Applications:**
            - lonote
            - manga-reader
            - save-manager
            - script-caller
            - syncer
            - your-player
            
            **Build info:**
            - Rust: ${{ env.RUST_VERSION }}
            - Build: ${{ github.run_number }}
            
            **Note for your-player on macOS and Linux:**
            Requires [mpv](https://mpv.io/) player installed
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}