name: Multi-Binary Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        crate: ["lonote", "manga-reader", "save-manager", "script-caller", "syncer", "your-player"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
            platform: linux
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
            platform: macos
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
            platform: windows

    name: Build ${{ matrix.crate }} for ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      # 精简的 Linux 依赖安装
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libgl1-mesa-dev \
            libasound2-dev \
            libfontconfig1-dev

      # 构建
      - name: Build ${{ matrix.crate }}
        run: |
          cargo build --release --target ${{ matrix.target }} --bin ${{ matrix.crate }}
        env:
          CARGO_TERM_COLOR: always

      # 准备发布文件（保持原样）
      - name: Prepare artifacts
        run: |
          mkdir -p release
          EXE_PATH="target/${{ matrix.target }}/release/${{ matrix.crate }}${{ matrix.ext }}"
          OUTPUT_NAME="${{ matrix.crate }}-${{ matrix.platform }}${{ matrix.ext }}"
          
          cp "$EXE_PATH" "release/$OUTPUT_NAME"

      # 符号剥离
      - name: Strip symbols
        if: matrix.os != 'windows-latest'
        run: |
          strip "release/${{ matrix.crate }}-${{ matrix.platform }}"

      # 上传
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.crate }}-${{ matrix.platform }}
          path: release/${{ matrix.crate }}-${{ matrix.platform }}*

  create-release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*'
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref_name }}"
          body: |
            ## Multi-platform executables
            
            **Available applications:**
            - lonote
            - manga-reader
            - save-manager
            - script-caller
            - syncer
            - your-player
            
            **Build info:**
            - Rust version: stable
            - Build date: ${{ github.run_number }}
          files: artifacts/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}